---
deployment:
  tasks:
    - export COMPOSER_HOME=/opt/cpanel/composer
    - export PATH=/opt/cpanel/composer/bin:$PATH
    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader
    - /usr/local/bin/php artisan migrate --force
    - /usr/local/bin/php artisan storage:link
    - /usr/local/bin/php artisan config:cache
    - /usr/local/bin/php artisan route:cache
    - /usr/local/bin/php artisan view:cache
    - /usr/local/bin/php artisan optimize
